arch:
  - arm64
os: linux
language: shell

services:
  - docker

env:
  global:
    - DOCKERHUB_TOOLBOX="nowaidavid/xbackbone-toolbox"
    - DOCKERHUB_XBACKBONE_PHP="nowaidavid/xbackbone-php:7.4-alpine-arm64"
    - DOCKERHUB_XBACKBONE_PHP_NGINX="nowaidavid/xbackbone-php-nginx:alpine-php7-arm64"
    - DOCKERHUB_XBACKBONE_IMAGE="nowaidavid/xbackbone-docker-arm64"

jobs:
  include:
    - stage: BuildXBackBoneToolboxImage
      if: (NOT (type IN (pull_request)))
      script:
        # Build image
        - docker build --no-cache -f ./upstream_images/toolbox/Dockerfile -t ${DOCKERHUB_TOOLBOX}:latest -t ${DOCKERHUB_TOOLBOX}:${TRAVIS_COMMIT} ./upstream_images/toolbox
        # Login to DockerHub
        - echo $DOCKERPASS | docker login -u $DOCKERUSER --password-stdin
        # Push all of the tags
        - docker push ${DOCKERHUB_TOOLBOX}:latest
        - docker push ${DOCKERHUB_TOOLBOX}:${TRAVIS_COMMIT}
    - stage: BuildXBackBonePHPImage
      if: (NOT (type IN (pull_request)))
      script:
        # Build image
        - docker build --no-cache -f ./upstream_images/php-official_7.4-alpine-arm64/Dockerfile -t ${DOCKERHUB_XBACKBONE_PHP} -t ${DOCKERHUB_XBACKBONE_PHP}-${TRAVIS_COMMIT} ./upstream_images/php-official_7.4-alpine-arm64
        # Login to DockerHub
        - echo $DOCKERPASS | docker login -u $DOCKERUSER --password-stdin
        # Push all of the tags
        - docker push ${DOCKERHUB_XBACKBONE_PHP}
        - docker push ${DOCKERHUB_XBACKBONE_PHP}-${TRAVIS_COMMIT}
    - stage: BuildXBackBonePHPNGINXImage
      if: (NOT (type IN (pull_request)))
      script:
        # Build image
        - docker build --no-cache -f ./upstream_images/php-nginx_alpine-php7-arm64/Dockerfile -t ${DOCKERHUB_XBACKBONE_PHP_NGINX} -t ${DOCKERHUB_XBACKBONE_PHP_NGINX}-${TRAVIS_COMMIT} ./upstream_images/php-nginx_alpine-php7-arm64
        # Login to DockerHub
        - echo $DOCKERPASS | docker login -u $DOCKERUSER --password-stdin
        # Push all of the tags
        - docker push ${DOCKERHUB_XBACKBONE_PHP_NGINX}-${TRAVIS_COMMIT}
        - docker push ${DOCKERHUB_XBACKBONE_PHP_NGINX}
    - stage: BuildXBackBoneIamge
      if: (NOT (type IN (pull_request)))
      script:
        # Build image
        - docker build --no-cache -f ./src/Dockerfile -t ${DOCKERHUB_XBACKBONE_IMAGE}:${TRAVIS_COMMIT} -t ${DOCKERHUB_XBACKBONE_IMAGE}:latest ./src
        # Login to DockerHub
        - echo $DOCKERPASS | docker login -u $DOCKERUSER --password-stdin
        # Push all of the tags
        - docker push ${DOCKERHUB_XBACKBONE_IMAGE}:${TRAVIS_COMMIT}
        - docker push ${DOCKERHUB_XBACKBONE_IMAGE}:latest
